[workspace]
resolver = "2"
members = ["crates/nlh", "ivy-suite"]

[workspace.package]
authors = ["Jacob Green"] 
edition = "2024"
rust-version = "1.93"
license = "Apache-2.0"
repository = "https://github.com/jg1011/ivy-suite"

[workspace.dependencies]
thiserror = "2"
anyhow = "1.0"
